# Generated by Django 4.1.2 on 2023-02-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hiredate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
